pipeline {
    agent any
    
    stages {
        stage('Restore') {
            steps {
                sh 'dotnet restore'
            }
        }
        stage('Build') {
            steps {
                sh 'dotnet build --configuration Release'
            }
        }
        stage('Test') {
            steps {
                sh 'dotnet test --configuration Release --logger "trx;LogFileName=test-results.trx"'
            }
        }
        stage('Publish Test Results') {
            steps {
                publishTestResults testResults: '**/test-results.trx'
            }
        }
    }
}
